---
language: python
cache: pip
dist: xenial
addons:
  apt:
    update: True
    sources:
      - sourceline: 'ppa:projectatomic/ppa'
    packages:
      - uidmap
      - podman
      - libffi-dev
      - git
before_install:
  - sudo mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf
  # we need to register travis to allow subuid/gid for the rootless execution
  # - echo "travis:110000:65535" | sudo tee /etc/subuid
  # - echo "travis:110000:65535" | sudo tee /etc/subgid

env:
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule
  # pip install -U git+https://github.com/ansible/molecule

script:
  - molecule test -s podman

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
