---
language: python
cache: pip
dist: xenial
addons:
  apt:
    update: True
    sources:
      - sourceline: 'ppa:projectatomic/ppa'
    packages:
      - uidmap
      - podman
before_install:
  - sudo mkdir -p /etc/containers
  - sudo sh -c "echo \"[registries.search]\nregistries = ['docker.io', 'quay.io']\" > /etc/containers/registries.conf"

env:
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install --upgrade molecule

script:
  - molecule test -s podman

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
