---
language: python
cache: pip
dist: xenial
before_install:
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common podman
  - sudo mkdir -p /etc/containers
  - sudo sh -c "echo \"[registries.search]\nregistries = ['docker.io', 'quay.io']\" > /etc/containers/registries.conf"

env:
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804

install:
  # Install test dependencies.
  - pip install molecule

script:
  - molecule test -s podman

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
