---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
